const HomeComponents = [
  //   {
  //     _id:"006",
  //     image:"./Image/card/card002.webp",
  //     title:"Green Forest Info Template",
  //     tag:"Info",
  //     link:"/info/green-forest-info-template",
  // },

  // {
  //     _id:"011",
  //     image:"../Image/teams/Teams002.webp"
  //     title:"Team hover layer card section",
  //     tag:"E-Card ",
  //     link:"/e-card/white-space-product-design-card",
  // },
  {
    _id: "066",
    image: "../Image/e-card/e-card001.webp",
    title: "E-commerce t-shirt design",
    tag: "e-card",
    link: "/e-card/e-commerce-t-shirt-design",
  },
  {
    _id: "065",
    image: "../Image/about/about008.webp",
    title: "Tailwind About us page free",
    tag: "about",
    link: "/about/tailwind-about-us-page-free",
  },
  {
    _id: "064",
    image: "../Image/contact/contact003.webp",
    title: "Contact us page design tailwind css",
    tag: "contact",
    link: "/contact/contact-us-page-design",
  },
  {
    _id: "063",
    image: "../Image/blog-card/blogcard001.webp",
    title: "Tailwind blog cards",
    tag: "blog-card",
    link: "/blog-card/tailwind-blog-cards",
  },
  {
    _id: "062",
    image: "../Image/testimonials/testimonials003.webp",
    title: "Testimonials tailwind design",
    tag: "testimonials",
    link: "/testimonials/testimonials-tailwind-design",
  },
  {
    _id: "061",
    image: "../Image/card/card009.webp",
    title: "Modern tailwind card design",
    tag: "card",
    link: "/card/modern-tailwind-card-design",
  },
  {
    _id: "060",
    image: "../Image/about/about007.webp",
    title: "Tailwind CSS About us page",
    tag: "about",
    link: "/about/tailwind-css-about-us-page",
  },
  {
    _id: "059",
    image: "../Image/table/table003.webp",
    title: "Table design in HTML examples",
    tag: "table",
    link: "/table/table-design",
  },
  {
    _id: "058",
    image: "../Image/testimonials/testimonials002.webp",
    title: "Testimonials tailwind component html",
    tag: "testimonials",
    link: "/testimonials/testimonials-tailwind",
  },
  {
    _id: "057",
    image: "../Image/dashboard-info/dashboard-info002.webp",
    title: "Dashboard Information",
    tag: "dashboard-info",
    link: "/dashboard-info/dashboard-information",
  },
  {
    _id: "056",
    image: "../Image/info/info003.webp",
    title: "Info number section css",
    tag: "info",
    link: "/info/info-number-section-css",
  },
  {
    _id: "055",
    image: "../Image/card/card008.webp",
    title: "css card design code",
    tag: "card",
    link: "/card/css-card-design-code",
  },
  {
    _id: "054",
    image: "../Image/footer/footer003.webp",
    title: "footer design html",
    tag: "footer",
    link: "/footer/footer-design-html-css",
  },
  {
    _id: "053",
    image: "../Image/teams/Teams003.webp",
    title: "Team section design",
    tag: "team",
    link: "/teams/team-section-design",
  },
  {
    _id: "052",
    image: "../Image/call-to-action/call002.webp",
    title: "call to action section ui design",
    tag: "call-to-action",
    link: "/call-to-action/call-to-action-section",
  },
  {
    _id: "051",
    image: "../Image/highlight/highlight004.webp",
    title: "highlight section css example",
    tag: "highlight",
    link: "/highlight/highlight-section-css",
  },
  {
    _id: "050",
    image: "../Image/info/info002.webp",
    title: "Info Design css",
    tag: "info",
    link: "/info/info-design-css",
  },
  {
    _id: "049",
    image: "../Image/about/about006.webp",
    title: "About page tailwind css",
    tag: "about",
    link: "/about/about-page-tailwind-css",
  },
  {
    _id: "048",
    image: "../Image/contact/contact002.webp",
    title: "Contact page tailwind css",
    tag: "contact",
    link: "/contact/contact-page-tailwind",
  },
  {
    _id: "047",
    image: "../Image/tab/tab001.webp",
    title: "Tab section tailwind css",
    tag: "tab",
    link: "/tab/tab-section-tailwind",
  },
  {
    _id: "046",
    image: "../Image/highlight/highlight003.webp",
    title: "Hide and show design tailwind css",
    tag: "highlight",
    link: "/highlight/hide-and-show-design",
  },
  {
    _id: "045",
    image: "../Image/skeleton/skeleton002.webp",
    title: "Blog Skeleton tailwind css",
    tag: "skeleton",
    link: "/skeleton/blog-skeleton-tailwind",
  },
  {
    _id: "045",
    image: "../Image/blog/blog002.webp",
    title: "News and events section",
    tag: "blog",
    link: "/blog/news-and-events-section",
  },
  {
    _id: "044",
    image: "../Image/highlight/highlight002.webp",
    title: "highlight section tailwind",
    tag: "highlight",
    link: "/highlight/highlight-section-tailwind",
  },
  {
    _id: "043",
    image: "../Image/testimonials/testimonials001.webp",
    title: "Testimonials Design Example",
    tag: "testimonials",
    link: "/testimonials/testimonials-design-examples",
  },
  {
    _id: "042",
    image: "../Image/services/services005.webp",
    title: "Services color card section tailwind css",
    tag: "services",
    link: "/services/services-card-section-tailwind",
  },
  {
    _id: "041",
    image: "../Image/faq/faq002.webp",
    title: "Faq table tailwind css",
    tag: "faq",
    link: "/faq/faq-table-tailwind",
  },
  {
    _id: "040",
    image: "../Image/skeleton/skeleton001.webp",
    title: "Skeleton table tailwind css",
    tag: "skeleton",
    link: "/skeleton/skeleton-table-tailwind",
  },
  {
    _id: "039",
    image: "../Image/services/services004.webp",
    title: "Our Services tailwind css",
    tag: "services",
    link: "/services/our-services-tailwind-css",
  },
  {
    _id: "038",
    image: "../Image/about/about005.webp",
    title: "About us page template",
    tag: "about",
    link: "/about/about-us-page-template",
  },
  {
    _id: "037",
    image: "../Image/blog/blog001.webp",
    title: "blog card design tailwind css",
    tag: "card",
    link: "/blog/blog-card-design",
  },
  {
    _id: "036",
    image: "../Image/hero/hero005.webp",
    title: "Tailwind background section",
    tag: "hero",
    link: "/hero/tailwind-background-section",
  },
  {
    _id: "035",
    image: "../Image/product/product001.webp",
    title: "Ecommerce product design tailwind",
    tag: "product",
    link: "/product/ecommerce-product",
  },
  {
    _id: "034",
    image: "../Image/table/table002.webp",
    title: "Tailwind table responsive",
    tag: "table",
    link: "/table/responsive-table",
  },
  {
    _id: "033",
    image: "../Image/faq/faq001.webp",
    title: "Simple faq sample design css",
    tag: "faq",
    link: "/faq/sample-faq-section",
  },
  {
    _id: "032",
    image: "../Image/card/card007.webp",
    title: "Recipe card template",
    tag: "card",
    link: "/card/recipe-card-template",
  },
  {
    _id: "031",
    image: "../Image/footer/footer002.webp",
    title: "Dark theme footer design",
    tag: "footer",
    link: "/footer/dark-theme-footer-design",
  },
  {
    _id: "030",
    image: "../Image/hero/hero004.webp",
    title: "Modern hero section design",
    tag: "hero",
    link: "/hero/modern-hero-section-design",
  },
  {
    _id: "029",
    image: "../Image/call-to-action/call001.webp",
    title: "Attractive Call to action",
    tag: "call-to-action",
    link: "/call-to-action/call-to-action-attractive",
  },
  {
    _id: "028",
    image: "../Image/card/card006.webp",
    title: "Curve card design",
    tag: "card",
    link: "/card/curve-card-design",
  },
  {
    _id: "027",
    image: "../Image/about/about004.webp",
    title: "Background cube about section",
    tag: "about",
    link: "/about/background-cube-about-section",
  },
  {
    _id: "026",
    image: "../Image/card/card005.webp",
    title: "Card layout section",
    tag: "card",
    link: "/card/card-layout-section",
  },
  {
    _id: "026",
    image: "../Image/news-letter/news-letter001.webp",
    title: "Subscribe newsletter attraction section",
    tag: "news-letter",
    link: "/subscribe-newsletter/subscribe-newsletter-attraction",
  },
  {
    _id: "025",
    image: "../Image/hero/hero003.webp",
    title: "Background Layer Hero Section",
    tag: "hero",
    link: "/hero/background-layer-hero-section",
  },

  {
    _id: "024",
    image: "../Image/services/services003.webp",
    title: "Icon Services Section",
    tag: "services",
    link: "/services/icon-services-section",
  },

  {
    _id: "023",
    image: "../Image/services/services002.webp",
    title: "Services section template",
    tag: "services",
    link: "/services/icon-side-alignment",
  },

  {
    _id: "022",
    image: "../Image/login/login002.webp",
    title: "Sample Login Page",
    tag: "login-in",
    link: "/login/sample-login-page",
  },

  {
    _id: "021",
    image: "../Image/login/login001.webp",
    title: "Standard Login Page",
    tag: "login-in",
    link: "/login/standard-login-page",
  },

  {
    _id: "020",
    image: "../Image/dashboard-info/dashboard-info001.webp",
    title: "Dashbaord Percentage Info Component",
    tag: "dashboard-info",
    link: "/dashboard-info/dashbaord-percentage-info",
  },

  {
    _id: "019",
    image: "../Image/404/404001.webp",
    title: "Page Not Found",
    tag: "404 page",
    link: "/404/page-not-found",
  },

  {
    _id: "018",
    image: "../Image/contact/contact001.webp",
    title: "Two grid Contact section",
    tag: "contact",
    link: "/contact/two-gird-contact-us",
  },
  {
    _id: "017",
    image: "../Image/highlight/highlight001.webp",
    title: "Highlight Capture",
    tag: "news-letter",
    link: "/highlight/highlight-capture",
  },

  {
    _id: "016",
    image: "../Image/card/card004.webp",
    title: "Semi Circle Design",
    tag: "card",
    link: "/card/semi-card-design",
  },

  {
    _id: "015",
    image: "../Image/footer/footer001.webp",
    title: "Landing page footer section",
    tag: "footer",
    link: "/footer/landing-page-footer",
  },

  {
    _id: "014",
    image: "../Image/card/card003.webp",
    title: "Center Align Circle Card section",
    tag: "card",
    link: "/card/center-align-circle-card",
  },

  {
    _id: "013",
    image: "../Image/hero/hero002.webp",
    title: "Two Grid Hero Section",
    tag: "hero",
    link: "/hero/two-grid-hero-section",
  },

  {
    _id: "012",
    image: "../Image/about/about003.webp",
    title: "Side Half Grid About Section",
    tag: "about",
    link: "/about/side-half-grid-about-section",
  },

  {
    _id: "011",
    image: "../Image/services/services001.webp",
    title: "Half Background layer services sections",
    tag: "services",
    link: "/card/half-background-layer-card",
  },

  {
    _id: "010",
    image: "../Image/teams/Teams002.webp",
    title: "Team hover layer card section",
    tag: "team",
    link: "/teams/team-hover-layer-card-section",
  },

  {
    _id: "009",
    image: "../Image/partners/partners001.webp",
    title: "Partners Hover effect scale section",
    tag: "partners",
    link: "/partners/partners-hover-effects-scale",
  },

  // {
  //   _id: "008",
  //   image: "../Image/about/about002.webp",
  //   title: "Formal About Section",
  //   tag: "about",
  //   link: "/about/formal-about-section",
  // },
  {
    _id: "007",
    image: "../Image/table/table001.webp",
    title: "Table with sort option",
    tag: "table",
    link: "/table/table-with-sort",
  },

  {
    _id: "006",
    image: "../Image/info/info001.webp",
    title: "Card Info Section Eight Grid",
    tag: "info",
    link: "/info/card-info-section-eight-grid",
  },

  {
    _id: "002",
    image: "../Image/teams/Teams001.webp",
    title: "Team Circle Hover Card",
    tag: "team",
    link: "/teams/team-circle-hover-card",
  },
  {
    _id: "003",
    image: "../Image/about/about001.webp",
    title: "Gallery frame Aboutus",
    tag: "about",
    link: "/about/gallery-frame-aboutus",
  },
  {
    _id: "001",
    image: "../Image/hero/hero001.webp",
    title: " Hero Section With Searching Options",
    tag: "hero",
    link: "/hero/hero-with-searchbar",
  },
  {
    _id: "004",
    image: "../Image/card/card001.webp",
    title: "Offer wise card section",
    tag: "card",
    link: "/card/offer-wise-card-section/",
  },
  {
    _id: "005",
    image: "../Image/card/card002.webp",
    title: "Three Grid card Template",
    tag: "card",
    link: "/card/three-grid-card-template",
  },
];

export default HomeComponents;
